Exercise 4
Systems-Development-and-Frameworks/dojo pull request #6
Opened 2020-12-08 09:33 UTC by jobegrabber

2020-12-08 13:18 UTC, noeljns requested changes
Overall a great implementation. As you already mentioned some tests are currently missing though.

2020-12-08 13:18 UTC, noeljns commented on backend/src/resolvers.js
> +        .then((passwordHash) => getUserAuthenticationToken(dataSources.db.createUser(name, email, passwordHash)))
Nice, you earned a star
> ⭐ For an implemented signup feature.

2020-12-08 13:18 UTC, noeljns commented on backend/src/resolvers.js
> +    }
I like the getUserAuthenticationToker method! A star
> ⭐ For an implemented login feature using JWT.

2020-12-08 13:18 UTC, noeljns commented on backend/src/db.js
> +    }
Great, a star
> ⭐ For unique email address validation.

2020-12-08 13:18 UTC, noeljns commented on backend/src/resolvers.js
> +          : new UserInputError('Invalid password provided!'))
Nice implementation, another star
> ⭐ For password validation.

2020-12-08 13:18 UTC, noeljns commented on backend/src/server.js
> +        userId: opts.authentication.checkUserAuthentication(req)
Another star
> ⭐ For assigning the authenticated user to a post in write and upvote mutations.
using getUserAuthenticationToken()

2020-12-08 13:19 UTC, powlaa approved these changes
Looks really good overall 👍

2020-12-08 13:19 UTC, powlaa commented on backend/src/authorisation.js
> +import { allow, rule, shield } from 'graphql-shield'
Didn't know there was already an allow from graphql-shield 👍 
Now we also used it in our permissions 😄

2020-12-08 13:19 UTC, powlaa commented on backend/src/authorisation.js
> +    downvotePost: isAuthenticated,
You could use a fallbackRule for this so any Mutation or Query you add will use this rule by default.

2020-12-08 13:19 UTC, powlaa commented on backend/src/server.spec.js
> +    describe('for unauthenticated users', () => {
Good test cases for unauthenticated users 👍

2021-01-07 12:46 UTC, medizinmensch approved these changes
Hi Jonas!

Sorry for the late review. It somehow slipped through. 

It looks very good. It's very easy to review your code because it's structure, minimal and easy to read. So thanks for that!

Additionally to what :star: you got below, you get the following:

:star:   For requesting a review and reviewing another team's PR according to the   instructions.
:star: For a successful rebase   on homework/main.
:star:   For not having security issues according to instructions.

That makes 10/10 :star: in total.

![Proud](https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif)

2021-01-07 12:46 UTC, medizinmensch commented on backend/src/resolvers.js
> +    },
:star: For an implemented signup   feature.
:star: For password validation.
:star:   For unique email address validation.

2021-01-07 12:46 UTC, medizinmensch commented on backend/src/resolvers.js
> +    }
:star: For an implemented login   feature using JWT.

2021-01-07 12:46 UTC, medizinmensch commented on backend/src/server.spec.js
> +  describe('login', () => {
:star:   For a software-tested login feature.

2021-01-07 12:46 UTC, medizinmensch commented on backend/src/server.spec.js
> +  describe('signup', () => {
:star:   For a software-tested signup feature.

2021-01-23 12:54 UTC, merged